class CreateCats < ActiveRecord::Migration[5.2]
  def change  
    create_table :cats do |t|
      t.string :name
      t.string :color
      t.string :gender
  end
end
## based on the diagram we made yesterday, cats would have name, color and gender.
## cat_id should be generated by itself because of ActiveRecord